export var l = [
    {
        restaurant : "食事",
        cafe : "カフェ",
        bar : "居酒屋",
        hotel : "宿泊",
        other : "その他",
        check : "お気に入りリスト",
        history : "屋台の歴史",
        root1 : "呉市の歴史を巡るコース",
        root2 : "居酒屋○次会コース（中通り内回り）",
        root3 : "夜のカフェバー巡りコース",
        search : "検索",
        sByText : "文字入力で探す",
        sByHash : "ハッシュタグから探す",
        sByRec : "あなたへのおすすめ",
        sResult : "検索結果",
        showRoot : "経路を表示",
        showReview : "レビュー",
        showMaps: "マップで確認",
        d_address: "住所",
        d_hours: "営業時間",
        d_week: "平日",
        d_holi: "土日祝日",
        d_regholi: "定休日",
        viewDetail: "詳細を見る >>",
        nofavs: "お気に入りに追加したスポットはありません。",
        favShops: "お気に入り",
        fav: "お気に入り",
        rem: "お気に入り解除",
        writeReview: "レビューを書く",
        title: "タイトル",
        review: "レビュー",
        send: "送信",
        nores: "検索結果はありません。",
    },
    {
        restaurant : "Resto",
        cafe : "Cafe",
        bar : "Bar",
        hotel : "Hotel",
        other : "Other",
        check : "Favorites list",
        history : "Street food history",
        root1 : "Kure City's History Touring Course",
        root2 : "Izakaya/After Party Course (Nakadori area)",
        root3 : "Night Café Bar Touring Course",
        search : "search",
        sByText : "Search with keywords",
        sByHash : "Search with hashtag",
        sByRec : "Recommendation for you",
        sResult : "Search results",
        showRoot : "Show direction",
        showReview : "Review",
        showMaps: "Check with map",
        d_address: "Address",
        d_hours: "Business hours",
        d_week: "Weekdays",
        d_holi: "Saturdays, Sundays, and holidays",
        d_regholi: "Regular holiday",
        viewDetail: "View the details >>",
        nofavs: "No favourite spot added yet.",
        favShops: "Added favourite spots",
        fav: "Favorite",
        rem: "Unfavorite",
        writeReview: "Write a Review",
        title: "Title",
        review: "Review",
        send: "Send",
        nores: "No results.",
    }
]

export var radio_l = [
    {
        Udon : "うどん",
        Alcohol : "アルコール",
        Curry : "カレー",
        Coffee : "コーヒー",
        Bread : "パン",
        TakeOut : "持ち帰り",
        Sweets : "スイーツ",
        CNoodle : "冷麺",
        JSweets : "和菓子",
        WSweets : "洋菓子",
        SetMenuMeal : "定食",
        Seafood : "海鮮",
        Ramen : "ラーメン",
        Okonomi : "お好み焼き",
        Steak : "ステーキ",
        FastFood : "ファストフード",
        FamilyRest : "ファミリーレストラン",
        Smoothie : "スムージー",
        Pasta : "パスタ",
        Soba : "そば",
        RiceOmlet : "オムレット",
        ChiniseFood : "中華",
        KoreanBBQ : "焼肉",
        Donut : "ドーナツ",
        Sushi : "寿司",
        SoftDrink : "清涼飲料",
        Hamburger : "ハンバーグ",
        Banquet : "宴会",
        Kushikatsu : "串カツ",
        Specialty : "呉の名物",
        Spanish : "スペイン料理",
        Takoyaki : "たこ焼き",
        Oyster : "牡蠣",
        Oden : "おでん",
        Monjayaki : "もんじゃ焼き",
        FishDishes : "魚料理",
        Yakitori : "焼き鳥",
        Italian : "イタリアン",
        Cake : "ケーキ",
        Sandwich : "サンドウィッチ",
        ShopWithSea : "海の見える店",
        FoodCourt : "フードコート",
        Gyoza : "餃子",
        Pickles : "漬物",
        Tsukudani : "佃煮",
        Earring : "ピアス",
        HomebredChicken : "地鶏",
        FriedChicken : "唐揚げ",
        Stall : "屋台",
        Sashimi : "刺身"
    },
    {
        Udon : "Udon",
        Alcohol : "Alcohol",
        Curry : "Curry",
        Coffee : "Coffee",
        Bread : "Bread",
        TakeOut : "Take out",
        Sweets : "Sweets",
        CNoodle : "Cold noodles",
        JSweets : "Japanese sweets",
        WSweets : "Western confectionery",
        SetMenuMeal : "Set menu meal",
        Seafood : "Seafood",
        Ramen : "Ramen",
        Okonomi : "Okonomiyaki",
        Steak : "Steak",
        FastFood : "Fast food",
        FamilyRest : "Family restaurant",
        Smoothie : "Smoothie",
        Pasta : "Pasta",
        Soba : "Soba",
        RiceOmlet : "Rice Omlet",
        ChiniseFood : "ChiniseFood",
        KoreanBBQ : "Korean barbecue",
        Donut : "Donut",
        Sushi : "Sushi",
        SoftDrink : "Soft Drink",
        Hamburger : "Hamburger steak",
        Banquet : "Banquet",
        Kushikatsu : "Kushikatsu",
        Specialty : "Specialty of Kure",
        Spanish : "Spanish",
        Takoyaki : "Takoyaki",
        Oyster : "Oyster",
        Oden : "Oden",
        Monjayaki : "Monjayaki",
        FishDishes : "Fish dishes",
        Yakitori : "Yakitori",
        Italian : "Italian",
        Cake : "Cake",
        Sandwich : "Sandwich",
        ShopWithSea : "Shop with a view of the sea",
        FoodCourt : "Food Court",
        Gyoza : "Gyoza",
        Pickles : "Pickles",
        Tsukudani : "Food boiled in soy sauce",
        Earring : "Earring",
        HomebredChicken : "Homebred chicken",
        FriedChicken : "Fried chicken",
        Stall : "Stall",
        Sashimi : "Sashimi"
    }
]

export var radio_lng = [
    ["うどん", "アルコール", "カレー", "コーヒー", "パン", "持ち帰り", "スイーツ", "冷麺",
     "和菓子", "洋菓子", "定食", "海鮮", "ラーメン", "お好み焼き", "ステーキ", "ファストフード",
     "ファミリーレストラン", "スムージー", "パスタ", "そば", "オムレット", "中華", "焼肉", 
     "ドーナツ", "寿司", "清涼飲料", "ハンバーグ", "宴会", "串カツ", "呉の名物", "スペイン料理",
     "たこ焼き", "牡蠣", "おでん", "もんじゃ焼き", "魚料理", "焼き鳥", "イタリアン", "ケーキ",
     "サンドウィッチ", "海の見える店", "フードコート", "餃子", "漬物", "佃煮", "ピアス", "地鶏",
     "唐揚げ", "屋台", "刺身"
    ],
    ["Udon", "Alcohol", "Curry", "Coffee", "Bread", "Take out", "Sweets", "Cold noodles",
     "Japanese sweets", "Western confectionery", "Set menu meal", "Seafood", "Ramen",
     "Okonomiyaki", "Steak", "Fast food", "Family restaurant", "Smoothie", "Pasta",
     "Soba", "Rice Omlet", "ChiniseFood", "Korean barbecue", "Donut", "Sushi", "Soft Drink",
     "Hamburger steak", "Banquet", "Kushikatsu", "Specialty of Kure", "Spanish", "Takoyaki",
     "Oyster", "Oden", "Monjayaki", "Fish dishes", "Yakitori", "Italian", "Cake", "Sandwich",
     "Shop with a view of the sea", "Food Court", "Gyoza", "Pickles", "Food boiled in soy sauce",
     "Earring", "Homebred chicken", "Fried chicken", "Stall", "Sashimi"
    ]
]