export var l = [
    {
        restaurant : "食事",
        cafe : "カフェ",
        bar : "居酒屋",
        hotel : "宿泊",
        other : "その他",
        check : "お気に入りリスト",
        history : "屋台の歴史",
        root1 : "呉市の歴史を巡るコース",
        root2 : "居酒屋○次会コース（中通り内回り）",
        root3 : "夜のカフェバー巡りコース",
        search : "検索",
        sByText : "文字入力で探す",
        sByHash : "ハッシュタグから探す",
        sByRec : "あなたへのおすすめ",
        sResult : "検索結果",
        showRoot : "経路を表示",
        showReview : "レビュー",
        showMaps: "マップで確認",
        d_address: "住所",
        d_hours: "営業時間",
        d_week: "平日",
        d_holi: "土日祝日",
        d_regholi: "定休日",
        viewDetail: "詳細を見る >>",
        nofavs: "お気に入りに追加したスポットはありません。",
        favShops: "お気に入り",
        fav: "お気に入り",
        rem: "お気に入り解除",
        writeReview: "レビューを書く",
        title: "タイトル",
        review: "レビュー",
        send: "送信",
        nores: "検索結果はありません。",
        help1: "画面の切り替え",
        help2: "マップページ",
        help3: "お店・観光スポットを地図上で探すことができます。",
        help4: "お店・観光スポット一覧",
        help5: "お店と観光スポットをジャンルごとに一覧で見ることができます。",
        help6: "その他・設定",
        help7: "お気に入りに入れた観光スポットや屋台の歴史を見たり，言語切り替えの設定ができます。",
        help8: "店舗詳細ページ",
        help9: "地図ページや一覧ページの「詳細を見る」を押すと表示されます。",
        help10: "詳細ページではお店の情報を見るほかにも、次のことができます。",
        help11: "(1)お気に入りに登録する（その他ページから確認できます）。",
        help12: "(2)地図でお店の位置を確認する。",
        help13: "(3)レビューを書く。",
        help14: "検索",
        help15: "地図ページや一覧ページの虫メガネマークを押すと表示されます。",
        help16: "検索ページでは次のことができます。",
        help17: "(1)お店・観光スポットの名前を検索",
        help18: "(2)ハッシュタグ（お店の特徴）から検索",
        help19: "(3)おすすめされたお店の情報を見る",
    },
    {
        restaurant : "Resto",
        cafe : "Cafe",
        bar : "Bar",
        hotel : "Hotel",
        other : "Other",
        check : "Favorites list",
        history : "Street food history",
        root1 : "Kure City's History Touring Course",
        root2 : "Izakaya/After Party Course (Nakadori area)",
        root3 : "Night Café Bar Touring Course",
        search : "search",
        sByText : "Search with keywords",
        sByHash : "Search with hashtag",
        sByRec : "Recommendation for you",
        sResult : "Search results",
        showRoot : "Show direction",
        showReview : "Review",
        showMaps: "Check with map",
        d_address: "Address",
        d_hours: "Business hours",
        d_week: "Weekdays",
        d_holi: "Saturdays, Sundays, and holidays",
        d_regholi: "Regular holiday",
        viewDetail: "View the details >>",
        nofavs: "No favourite spot added yet.",
        favShops: "Added favourite spots",
        fav: "Favorite",
        rem: "Unfavorite",
        writeReview: "Write a Review",
        title: "Title",
        review: "Review",
        send: "Send",
        nores: "No results.",
        help1: "Screen switching",
        help2: "Map page",
        help3: "You can find stores and sightseeing spots on the map.",
        help4: "List of Shops and Sightseeing spots",
        help5: "You can see the stores and sightseeing spots listed by genre.",
        help6: "Other / Settings",
        help7: "You can see the history of stalls and your favorite spots, and set the language switch.",
        help8: "Store Details Page",
        help9: 'Press "View Details" on the map page or list page.',
        help10: "Besides you can see the information about the store on the detail page:",
        help11: "(1) Bookmark it to your favorites (can be found on the Other/Setting page).",
        help12: "(2)Check the location of the store on the map.",
        help13: "(3)Write a review.",
        help14: "Search",
        help15: "Press the magnifying glass symbol on the map page or list page.",
        help16: "On the search page you can",
        help17: "(1)Search for the name of a store or sightseeing spot of interest",
        help18: "(2)Search by hashtag (store features)",
        help19: "(3) See information about the recommended stores or sightseeing spots",
    }
]

export var radio_lng = [
    ["うどん", "アルコール", "カレー", "コーヒー", "パン", "持ち帰り", "スイーツ", "冷麺",
     "和菓子", "洋菓子", "定食", "海鮮", "ラーメン", "お好み焼き", "ステーキ", "ファストフード",
     "ファミリーレストラン", "スムージー", "パスタ", "そば", "オムレット", "中華", "焼肉", 
     "ドーナツ", "寿司", "清涼飲料", "ハンバーグ", "宴会", "串カツ", "呉の名物", "スペイン料理",
     "たこ焼き", "牡蠣", "おでん", "もんじゃ焼き", "魚料理", "焼き鳥", "イタリアン", "ケーキ",
     "サンドウィッチ", "海の見える店", "フードコート", "餃子", "漬物", "佃煮", "ピアス", "地鶏",
     "唐揚げ", "屋台", "刺身", "観光", "戦艦大和", "歴史", "軍艦", "交通", "ゲストハウス",
     "ボウリング", "買い物", "カラオケ", "公園", "潜水艦", "イベント", "体験型",
     "桜の名所", "ホテル", "温泉", "ビジネスホテル", "プール", "ロケ地", "広場", "スケボー"
    ],
    ["Udon", "Alcohol", "Curry", "Coffee", "Bread", "Take out", "Sweets", "Cold noodles",
     "Japanese sweets", "Western confectionery", "Set menu meal", "Seafood", "Ramen",
     "Okonomiyaki", "Steak", "Fast food", "Family restaurant", "Smoothie", "Pasta",
     "Soba", "Rice Omlet", "ChiniseFood", "Korean barbecue", "Donut", "Sushi", "Soft Drink",
     "Hamburger steak", "Banquet", "Kushikatsu", "Specialty of Kure", "Spanish", "Takoyaki",
     "Oyster", "Oden", "Monjayaki", "Fish dishes", "Yakitori", "Italian", "Cake", "Sandwich",
     "Shop with a view of the sea", "Food Court", "Gyoza", "Pickles", "Food boiled in soy sauce",
     "Earring", "Homebred chicken", "Fried chicken", "Stall", "Sashimi", "Sightseeing", "Yamato",
     "History", "Battleships", "Traffic", "Guest house", "Bowling", "Shopping", "Karaoke", "Park",
     "Submarine", "Event", "Experiential", "Cherry blossom", "Hotel", "Hot spring", "Business hotel",
     "Pool", "Filming location", "Plaza", "Skateboarding",
    ]
]